package cse214hw2;

public class DISTest {
    public static void main(String[] args) {
        // Test cases generated by ChatGPT.
        // ChatGPT Version September 25, 2023
        // Prompt:
        // "Given this implementation of a tree-backed Integer set,
        //  generate test cases for add, contains, remove, and size.
        //  <insert entirety of DynamicIntegerSet.java>"

        // Create an instance of DynamicIntegerSet
        DynamicIntegerSet set = new DynamicIntegerSet();

        // Test Case 1: Add elements
        System.out.println("Test Case 1: Add elements");
        System.out.println("Adding 5: " + set.add(5)); // true
        System.out.println("Adding 3: " + set.add(3)); // true
        System.out.println("Adding 7: " + set.add(7)); // true
        System.out.println("Adding 5 again: " + set.add(5)); // false (already exists)
        System.out.println("Adding 4: " + set.add(4)); // true
        System.out.println("Adding 6: " + set.add(6)); // true
        System.out.println("Adding 8: " + set.add(8)); // true
        System.out.println("Adding 2: " + set.add(2)); // true
        System.out.println();

        // Test Case 2: Contains elements
        System.out.println("Test Case 2: Contains elements");
        System.out.println("Contains 5: " + set.contains(5)); // true
        System.out.println("Contains 1: " + set.contains(1)); // false
        System.out.println("Contains 8: " + set.contains(8)); // true
        System.out.println("Contains 0: " + set.contains(0)); // false
        System.out.println();

        // Test Case 3: Remove elements
        System.out.println("Test Case 3: Remove elements");
        System.out.println("Removing 4: " + set.remove(4)); // true
        System.out.println("Removing 7: " + set.remove(7)); // true
        System.out.println("Removing 10: " + set.remove(10)); // false (does not exist)
        System.out.println();

        // Test Case 4: Check size
        System.out.println("Test Case 4: Check size");
        System.out.println("Size of the set: " + set.size()); // 5
    }
}
